% See the forward function for description
function [derX,derW,derB]=bwd_holed_simple(X,W,B,derOutput,obj)
holedW = get_holed_weights(W,obj);
[derX,derW,derB] = vl_nnconv(...
    X, holedW, B, derOutput, ...
    'pad', obj.pad, ...
    'stride', obj.stride, ...
    obj.opts{:}) ;
derW=derW(1:obj.hole:end,1:obj.hole:end,:,:);
