% The naive implementation of holed convolution
% Create a larger weights filter with zeros in the holes location
% Will most likely fail when the hole is large
function Y=fwd_holed_simple(X,W,B,obj)
holedW = get_holed_weights(W,obj);
Y = vl_nnconv(...
    X, holedW, B, ...
    'pad', obj.pad, ...
    'stride', obj.stride, ...
    obj.opts{:}) ;
